[package]
name = "rust-vulkan-engine"
version = "0.1.0"
authors = ["Daniel Wart <dman.wart@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
cgmath = "0.18.0"
ash = { git = "https://github.com/MaikKlein/ash.git" }
ash-window = { git = "https://github.com/MaikKlein/ash.git" }
image = "0.23.14"
tobj = "3.0.1"
vk-mem = { path = "../vk-mem-rs" }