[package]
name = "rust-vulkan-engine"
version = "0.1.0"
authors = ["Daniel Wart <dman.wart@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
image = {version = "0.23.14", default-features = false, features = ["png", "hdr"]}
gltf = "0.16.0"
fastrand = "1.5.0"

erupt = "0.20.0+190"
vk-mem-erupt = {git = "https://github.com/onein50million/vk-mem-erupt.git"}
nalgebra = "0.29.0"
