pub const PARTY_NAMES: &[&str] = &[
    "Moderate Nation Party",
    "Universal Regulation League",
    "Traditional Right Wing Party",
    "Democratic Movement",
    "Fanatical Labor Group",
    "Eastern Equilibrium Party",
    "Leading Unity Union",
    "Industrial Democratic Coalition",
    "Collective Abolition Party",
    "Common Communion Coalition",
    "Organized Appreciation League",
    "Global Red Party",
    "Global Egalitarianism Party",
    "Leading Future Movement",
    "Modern Voice League",
    "Segregation Party",
    "People's Future Union",
    "Unified Civil Rights League",
    "Permanent Life Party",
    "Leading Freedom Party,",
    "Western Workers Party",
    "Social Taxpayer Coalition",
    "Contemporary Red Party",
    "Advanced Opportunity Party",
    "Revolutionary Affinity League",
    "Traditional Liberty Group",
    "National Regulation Coalition",
    "Prime Formation Coalition",
    "Rational Science Party",
    "Sovereign Constitution Party,",
    "Western Workers Party",
    "Social Taxpayer Coalition",
    "Contemporary Red Party",
    "Advanced Opportunity Party",
    "Revolutionary Affinity League",
    "Traditional Liberty Group",
    "National Regulation Coalition",
    "Prime Formation Coalition",
    "Rational Science Party",
    "Sovereign Constitution Party,",
    "Northern Justice Movement",
    "People's Appreciation Party",
    "Transformation Group",
    "Prime Legislation Movement",
    "Southern Taxpayer Union",
    "New Constitution Coalition",
    "Lawful Fascist Party",
    "Federal Conservative Movement",
    "Moderate Conservative Group",
    "Federal Denizen Party",
];
