#version 450
layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(set = 0, binding = 0, rgba32i) uniform iimage3D inImage;
layout(set = 0, binding = 1, r8ui) writeonly uniform uimage3D outImage;

void main(){
    ivec3 seed_position = imageLoad(inImage, ivec3(gl_GlobalInvocationID)).rgb;

    imageStore(outImage, ivec3(gl_GlobalInvocationID), uvec4(distance(seed_position, ivec3(gl_GlobalInvocationID))));
}