name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  GLSLC_URL: "https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/windows/continuous_release_2017/374/20210924-175819/install.zip"



jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: download glslc
      run: Invoke-WebRequest $GLSLC_URL
    - name: Build shaders
      run: |
        ls ../
        glslc.exe shader.vert -o vert.spv
        glslc.exe shader.frag -o frag.spv
        glslc.exe shader.comp -o comp.spv
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive fragment
      uses: actions/upload-artifact@v2.2.4
      with:
        name: executable
        path: |
          target/debug/rust-vulkan-engine.exe
          shaders/*.spv
      
