name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CMAKE_BUILD_TYPE: Release



jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: download and build glslc
      run: |
        git clone https://github.com/google/shaderc
        $SOURCE_DIR=Resolve-Path shaderc
        cd $SOURCE_DIR
        ./utils/git-sync-deps
        cd $SOURCE_DIR/
        mkdir cool-build-directory
        cd cool-build-directory
        cmake $SOURCE_DIR -Dgtest_disable_pthreads=ON
        cmake --build . --config Release
        ls
    - name: Build shaders
      run: |
        ls ../
        glslc.exe shader.vert -o vert.spv
        glslc.exe shader.frag -o frag.spv
        glslc.exe shader.comp -o comp.spv
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive fragment
      uses: actions/upload-artifact@v2.2.4
      with:
        name: executable
        path: |
          target/debug/rust-vulkan-engine.exe
          shaders/*.spv
      
