name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always



jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: download glslc
      uses: actions/checkout@v2
      with: 
        repository: 'google/shaderc'
    - name: build glslc
      run: |
        ls
        ../ls
        cd ../shaderc
        cmake
        cd ../rust-vulkan-engine
    - name: Build shaders #shouldn't work
      run: |
        ../ls
        glslc.exe shader.vert -o vert.spv
        glslc.exe shader.frag -o frag.spv
        glslc.exe shader.comp -o comp.spv
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive fragment
      uses: actions/upload-artifact@v2.2.4
      with:
        name: executable
        path: |
          target/debug/rust-vulkan-engine.exe
          shaders/*.spv
      
