name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always



jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: download and build glslc
      run: |
        $env:SOURCE_DIR="/cool-source-dir"
        git clone https://github.com/google/shaderc $SOURCE_DIR
        cd $SOURCE_DIR
        ls
        ./utils/git-sync-deps
        cd $SOURCE_DIR/
        mkdir cool-build-directory
        cd cool-build-directory
        cmake -GNinja -DCMAKE_BUILD_TYPE={Debug|Release|RelWithDebInfo} $SOURCE_DIR
        ninja
        cd ../rust-vulkan-engine
    - name: Build shaders
      run: |
        ls ../
        glslc.exe shader.vert -o vert.spv
        glslc.exe shader.frag -o frag.spv
        glslc.exe shader.comp -o comp.spv
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive fragment
      uses: actions/upload-artifact@v2.2.4
      with:
        name: executable
        path: |
          target/debug/rust-vulkan-engine.exe
          shaders/*.spv
      
